importing modules

In [1]:
import pandas as pd
import numpy as np

Basic Describe and Null Check of both dataset

In [2]:
district = pd.read_csv("./datasets/nepal_district_centroids.csv")
dengu_temporal = pd.read_csv("./datasets/dengu_temporal.csv")

print(f"Length of District Data: {len(district)}")
print("------------------------------------")
print("District Data Described: ")
display(district.describe())
print("------------------------------------")
print("District Data Null Vals")
display(district.isnull().sum())

print("\n------------------------------------\n------------------------------------\n")

print(f"Length of Temporal Data: {len(dengu_temporal)}")
print("------------------------------------")
print("Temporal Data Described: ")
display(dengu_temporal.describe())
print("------------------------------------")
print("Temporal Data Null Vals")
display(dengu_temporal.isnull().sum())

Length of District Data: 77
------------------------------------
District Data Described:

       LONGITUDE   LATITUDE
count  77.000000  77.000000
mean   84.231803  28.013663
std     2.161370   0.878358
min    80.324299  26.579753
25%    82.420482  27.331392
50%    84.227051  27.918388
75%    85.946616  28.672759
max    87.916711  30.031208

------------------------------------
District Data Null Vals

DISTRICT     0
LONGITUDE    0
LATITUDE     0
dtype: int64

------------------------------------
------------------------------------

Length of Temporal Data: 2963
------------------------------------
Temporal Data Described:

       FAO_GAUL_code  IBGE_code         Year  dengue_total
count    2963.000000        0.0  2963.000000   2963.000000
mean    21204.227135        NaN  2022.760715     93.370570
std      4924.717253        NaN     1.494684    718.547273
min       175.000000        NaN  2005.000000      0.000000
25%     22352.000000        NaN  2022.000000      0.000000
50%     22357.000000        NaN  2023.000000      2.000000
75%     22363.000000        NaN  2024.000000     14.000000
max     22364.000000        NaN  2025.000000  14534.000000

------------------------------------
Temporal Data Null Vals

adm_0_name                         0
adm_1_name                       184
adm_2_name                       161
full_name                          0
ISO_A0                             0
FAO_GAUL_code                      0
RNE_iso_code                       0
IBGE_code                       2963
calendar_start_date                0
calendar_end_date                  0
Year                               0
dengue_total                       0
case_definition_standardised       0
S_res                              0
T_res                              0
UUID                               0
region                             0
dtype: int64

In [3]:
print("Temporal Data")
display(dengu_temporal.dtypes)

Temporal Data

adm_0_name                          str
adm_1_name                          str
adm_2_name                          str
full_name                           str
ISO_A0                              str
FAO_GAUL_code                     int64
RNE_iso_code                        str
IBGE_code                       float64
calendar_start_date                 str
calendar_end_date                   str
Year                              int64
dengue_total                      int64
case_definition_standardised        str
S_res                               str
T_res                               str
UUID                                str
region                              str
dtype: object

In [4]:
# Print first 5 data of temporal
print('Temporal Data structure')
dengu_temporal.head()

Temporal Data structure

,adm_0_name,adm_1_name,adm_2_name,full_name,ISO_A0,FAO_GAUL_code,RNE_iso_code,IBGE_code,calendar_start_date,calendar_end_date,Year,dengue_total,case_definition_standardised,S_res,T_res,UUID,region
0,NEPAL,NaN,SYANGJA,"NEPAL, SYANGJA",NPL,22364,NPL,NaN,2016-01-01,2016-12-31,2016,1,Total,Admin1,Year,MOH-NPL-2016-Y01-00,SEARO
1,NEPAL,NaN,DHADING,"NEPAL, DHADING",NPL,22353,NPL,NaN,2016-01-01,2016-12-31,2016,4,Total,Admin1,Year,MOH-NPL-2016-Y01-00,SEARO
2,NEPAL,NaN,BARA,"NEPAL, BARA",NPL,22353,NPL,NaN,2016-01-01,2016-12-31,2016,4,Total,Admin1,Year,MOH-NPL-2016-Y01-00,SEARO
3,NEPAL,NaN,DANG,"NEPAL, DANG",NPL,22360,NPL,NaN,2016-01-01,2016-12-31,2016,8,Total,Admin1,Year,MOH-NPL-2016-Y01-00,SEARO
4,NEPAL,NaN,RUKUM,"NEPAL, RUKUM",NPL,22360,NPL,NaN,2016-01-01,2016-12-31,2016,1,Total,Admin1,Year,MOH-NPL-2016-Y01-00,SEARO

Show Different value counts in the Temporal Data

In [5]:
display(dengu_temporal["case_definition_standardised"].value_counts())
display(dengu_temporal["T_res"].value_counts())

case_definition_standardised
Total        2953
Confirmed      10
Name: count, dtype: int64

T_res
Month    2873
Year       49
Week       41
Name: count, dtype: int64

In [6]:
# remove Yearly and weekly dataset as they carry 3% only data in whole dataset
dengu_temporal = dengu_temporal[(dengu_temporal["T_res"]!="Year") & (dengu_temporal["T_res"]!="Week")]

Add new Location Column and remove unnecessary

In [7]:
# Location In Dataset is Added 
dengu_temporal["Location"] = dengu_temporal["adm_2_name"].fillna(dengu_temporal["full_name"].str.split(",").str[-1])

# Remove unnecessary Columns
dengu_temporal = dengu_temporal.drop(
    columns="adm_0_name,adm_1_name,adm_2_name,full_name,ISO_A0,FAO_GAUL_code,RNE_iso_code,IBGE_code,S_res,region,UUID,case_definition_standardised,T_res".split(",")
)

dengu_temporal[:10]

   calendar_start_date calendar_end_date  Year  dengue_total Location
27          2018-05-01        2018-05-31  2018             1    NEPAL
28          2018-06-01        2018-06-30  2018             7    NEPAL
29          2018-07-01        2018-07-31  2018            15    NEPAL
30          2018-08-01        2018-08-31  2018            34    NEPAL
31          2018-09-01        2018-09-30  2018            30    NEPAL
32          2018-10-01        2018-10-31  2018            21    NEPAL
48          2016-09-01        2016-09-30  2016             2    NEPAL
49          2016-11-01        2016-11-30  2016           442    NEPAL
50          2016-12-01        2016-12-31  2016            10    NEPAL
51          2017-01-01        2017-01-31  2017             3    NEPAL

Extract month using start date. Then delete other unnecessary dates

In [8]:
# convert to date time format
dengu_temporal["calendar_start_date"] = pd.to_datetime(dengu_temporal["calendar_start_date"])

#month map
month_map = {
    1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr", 
    5: "May", 6: "Jun", 7: "Jul", 8: "Aug", 
    9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec"
}

dengu_temporal["Month"] = dengu_temporal["calendar_start_date"].dt.month.map(month_map)
dengu_temporal.head()

   calendar_start_date calendar_end_date  Year  dengue_total Location Month
27          2018-05-01        2018-05-31  2018             1    NEPAL   May
28          2018-06-01        2018-06-30  2018             7    NEPAL   Jun
29          2018-07-01        2018-07-31  2018            15    NEPAL   Jul
30          2018-08-01        2018-08-31  2018            34    NEPAL   Aug
31          2018-09-01        2018-09-30  2018            30    NEPAL   Sep

In [9]:
# show all location counts
display(dengu_temporal["Location"].value_counts())
print(f'Total Length = {len(dengu_temporal)}')
dengu_temporal.head()

Location
NEPAL           101
ACHHAM           36
ARGHAKHANCHI     36
BAGLUNG          36
BAITADI          36
               ...
SYANGJA          36
TANAHU           36
TAPLEJUNG        36
TERHATHUM        36
UDAYAPUR         36
Name: count, Length: 78, dtype: int64

Total Length = 2873

   calendar_start_date calendar_end_date  Year  dengue_total Location Month
27          2018-05-01        2018-05-31  2018             1    NEPAL   May
28          2018-06-01        2018-06-30  2018             7    NEPAL   Jun
29          2018-07-01        2018-07-31  2018            15    NEPAL   Jul
30          2018-08-01        2018-08-31  2018            34    NEPAL   Aug
31          2018-09-01        2018-09-30  2018            30    NEPAL   Sep

The Location Nepal can give specific location and it only contains 3.5% of total dataset we delete rows

In [10]:
dengu_temporal = dengu_temporal[dengu_temporal["Location"]!="NEPAL"]
dengu_temporal.head()

,calendar_start_date,calendar_end_date,Year,dengue_total,Location,Month
110,2022-01-01,2022-01-31,2022,0,ACHHAM,Jan
111,2022-01-01,2022-01-31,2022,0,ARGHAKHANCHI,Jan
112,2022-01-01,2022-01-31,2022,0,BAGLUNG,Jan
113,2022-01-01,2022-01-31,2022,0,BAITADI,Jan
114,2022-01-01,2022-01-31,2022,1,BAJHANG,Jan

### Merge latitude and longitude data to dengu data

For further finding weather using latitude, longitude

In [11]:
merged_df = pd.merge(dengu_temporal, district, left_on="Location", right_on="DISTRICT", how="left")

print(f"Length of Merged df = {len(merged_df)}")
merged_df.head()

Length of Merged df = 2772

,calendar_start_date,calendar_end_date,Year,dengue_total,Location,Month,DISTRICT,LONGITUDE,LATITUDE
0,2022-01-01,2022-01-31,2022,0,ACHHAM,Jan,ACHHAM,81.299520,29.113168
1,2022-01-01,2022-01-31,2022,0,ARGHAKHANCHI,Jan,ARGHAKHANCHI,83.076443,27.918388
2,2022-01-01,2022-01-31,2022,0,BAGLUNG,Jan,BAGLUNG,83.256547,28.345703
3,2022-01-01,2022-01-31,2022,0,BAITADI,Jan,BAITADI,80.571334,29.505689
4,2022-01-01,2022-01-31,2022,1,BAJHANG,Jan,BAJHANG,81.180034,29.707134

In [12]:
merged_df.drop(columns=["DISTRICT"], inplace=True)
merged_df.head()

,calendar_start_date,calendar_end_date,Year,dengue_total,Location,Month,LONGITUDE,LATITUDE
0,2022-01-01,2022-01-31,2022,0,ACHHAM,Jan,81.299520,29.113168
1,2022-01-01,2022-01-31,2022,0,ARGHAKHANCHI,Jan,83.076443,27.918388
2,2022-01-01,2022-01-31,2022,0,BAGLUNG,Jan,83.256547,28.345703
3,2022-01-01,2022-01-31,2022,0,BAITADI,Jan,80.571334,29.505689
4,2022-01-01,2022-01-31,2022,1,BAJHANG,Jan,81.180034,29.707134

In [13]:
print(merged_df["LATITUDE"].isna().sum())
print(merged_df["LONGITUDE"].isna().sum())
print(len(merged_df))

288
288
2772

In [14]:
merged_df = merged_df.dropna(subset=["LATITUDE", "LONGITUDE"])

merged_df["calendar_start_date"] = pd.to_datetime(
    merged_df["calendar_start_date"],
    errors="coerce"
)

merged_df["calendar_end_date"] = pd.to_datetime(
    merged_df["calendar_end_date"],
    errors="coerce"
)

print(merged_df[["calendar_start_date", "calendar_end_date"]].dtypes)

calendar_start_date    datetime64[us]
calendar_end_date      datetime64[us]
dtype: object

### Extract Weather Data and summarize for ML purpose

Referenced from and used from https://open-meteo.com/en/docs/historical-weather-api. Modified to function.

In [15]:
import openmeteo_requests
import pandas as pd

# Initialize Open-Meteo client
openmeteo = openmeteo_requests.Client()


def get_weather_summary(start_dates, end_dates, latitudes, longitudes):
    # Open-Meteo archive API
    url = "https://archive-api.open-meteo.com/v1/archive"

    # Store results
    results = []

    i=1
    # Iterate through each location/date range
    for start, end, lat, lon in zip(start_dates, end_dates, latitudes, longitudes):
        
        start = pd.to_datetime(start).strftime("%Y-%m-%d")
        end = pd.to_datetime(end).strftime("%Y-%m-%d")

        # Request parameters
        params = {
            "latitude": lat,
            "longitude": lon,
            "start_date": start,
            "end_date": end,
            "daily": [
                "temperature_2m_mean",
                "rain_sum",
                "relative_humidity_2m_mean",
                "soil_moisture_0_to_100cm_mean",
                "soil_temperature_0_to_100cm_mean",
                "snowfall_sum",
                "precipitation_sum",
            ],
        }

        # Send request
        response = openmeteo.weather_api(url, params=params)[0]
        daily = response.Daily()

        # Save the average values for this request
        results.append({
            "latitude": lat,
            "longitude": lon,
            "start_date": start,
            "end_date": end,
            "monthly_avg_temperature": daily.Variables(0).ValuesAsNumpy().mean(),
            "avg_daily_rain": daily.Variables(1).ValuesAsNumpy().mean(),
            "avg_daily_humidity": daily.Variables(2).ValuesAsNumpy().mean(),
            "avg_daily_soil_moisture": daily.Variables(3).ValuesAsNumpy().mean(),
            "avg_daily_soil_temperature": daily.Variables(4).ValuesAsNumpy().mean(),
            "avg_daily_snowfall": daily.Variables(5).ValuesAsNumpy().mean(),
            "avg_daily_precipitation": daily.Variables(6).ValuesAsNumpy().mean(),
        })
        
        print(f"completed {i} ....")
        i+=1

    # Return one row per input
    return pd.DataFrame(results)

In [16]:
weather_data = get_weather_summary(
    merged_df["calendar_start_date"],
    merged_df["calendar_end_date"],
    merged_df["LATITUDE"],
    merged_df["LONGITUDE"]
)

completed 1 ....
completed 2 ....
completed 3 ....
completed 4 ....
completed 5 ....
completed 6 ....
completed 7 ....
completed 8 ....
completed 9 ....
completed 10 ....
completed 11 ....
completed 12 ....
completed 13 ....
completed 14 ....
completed 15 ....
completed 16 ....
completed 17 ....
completed 18 ....
completed 19 ....
completed 20 ....
completed 21 ....
completed 22 ....
completed 23 ....
completed 24 ....
completed 25 ....
completed 26 ....
completed 27 ....
completed 28 ....
completed 29 ....
completed 30 ....
completed 31 ....
completed 32 ....
completed 33 ....
completed 34 ....
completed 35 ....
completed 36 ....
completed 37 ....
completed 38 ....
completed 39 ....
completed 40 ....
completed 41 ....
completed 42 ....
completed 43 ....
completed 44 ....
completed 45 ....
completed 46 ....
completed 47 ....
completed 48 ....
completed 49 ....
completed 50 ....
completed 51 ....
completed 52 ....
completed 53 ....
completed 54 ....
completed 55 ....
completed 56 ....
completed 57 ....
completed 58 ....
completed 59 ....
completed 60 ....
completed 61 ....
completed 62 ....
completed 63 ....
completed 64 ....
completed 65 ....
completed 66 ....
completed 67 ....
completed 68 ....
completed 69 ....
completed 70 ....
completed 71 ....
completed 72 ....
completed 73 ....
completed 74 ....
completed 75 ....
completed 76 ....
completed 77 ....
completed 78 ....
completed 79 ....
completed 80 ....
completed 81 ....
completed 82 ....
completed 83 ....
completed 84 ....
completed 85 ....
completed 86 ....
completed 87 ....
completed 88 ....
completed 89 ....
completed 90 ....
completed 91 ....
completed 92 ....
completed 93 ....
completed 94 ....
completed 95 ....
completed 96 ....
completed 97 ....
completed 98 ....
completed 99 ....
completed 100 ....
completed 101 ....
completed 102 ....
completed 103 ....
completed 104 ....
completed 105 ....
completed 106 ....
completed 107 ....
completed 108 ....
completed 109 ....
completed 110 ....
completed 111 ....
completed 112 ....
completed 113 ....
completed 114 ....
completed 115 ....
completed 116 ....
completed 117 ....
completed 118 ....
completed 119 ....
completed 120 ....
completed 121 ....
completed 122 ....
completed 123 ....
completed 124 ....
completed 125 ....
completed 126 ....
completed 127 ....
completed 128 ....
completed 129 ....
completed 130 ....
completed 131 ....
completed 132 ....
completed 133 ....
completed 134 ....
completed 135 ....
completed 136 ....
completed 137 ....
completed 138 ....
completed 139 ....
completed 140 ....
completed 141 ....
completed 142 ....
completed 143 ....
completed 144 ....
completed 145 ....
completed 146 ....
completed 147 ....
completed 148 ....
completed 149 ....
completed 150 ....
completed 151 ....
completed 152 ....
completed 153 ....
completed 154 ....
completed 155 ....
completed 156 ....
completed 157 ....
completed 158 ....
completed 159 ....
completed 160 ....
completed 161 ....
completed 162 ....
completed 163 ....
completed 164 ....
completed 165 ....
completed 166 ....
completed 167 ....
completed 168 ....
completed 169 ....
completed 170 ....
completed 171 ....
completed 172 ....
completed 173 ....
completed 174 ....
completed 175 ....
completed 176 ....
completed 177 ....
completed 178 ....
completed 179 ....
completed 180 ....
completed 181 ....
completed 182 ....
completed 183 ....
completed 184 ....
completed 185 ....
completed 186 ....
completed 187 ....
completed 188 ....
completed 189 ....
completed 190 ....
completed 191 ....
completed 192 ....
completed 193 ....
completed 194 ....
completed 195 ....
completed 196 ....
completed 197 ....
completed 198 ....
completed 199 ....
completed 200 ....
completed 201 ....
completed 202 ....
completed 203 ....
completed 204 ....
completed 205 ....
completed 206 ....
completed 207 ....
completed 208 ....
completed 209 ....
completed 210 ....
completed 211 ....
completed 212 ....
completed 213 ....
completed 214 ....
completed 215 ....
completed 216 ....
completed 217 ....
completed 218 ....
completed 219 ....
completed 220 ....
completed 221 ....
completed 222 ....
completed 223 ....
completed 224 ....
completed 225 ....
completed 226 ....
completed 227 ....
completed 228 ....
completed 229 ....
completed 230 ....
completed 231 ....
completed 232 ....
completed 233 ....
completed 234 ....
completed 235 ....
completed 236 ....
completed 237 ....
completed 238 ....
completed 239 ....
completed 240 ....
completed 241 ....
completed 242 ....
completed 243 ....
completed 244 ....
completed 245 ....
completed 246 ....
completed 247 ....
completed 248 ....
completed 249 ....
completed 250 ....
completed 251 ....
completed 252 ....
completed 253 ....
completed 254 ....
completed 255 ....
completed 256 ....
completed 257 ....
completed 258 ....
completed 259 ....
completed 260 ....
completed 261 ....
completed 262 ....
completed 263 ....
completed 264 ....
completed 265 ....
completed 266 ....
completed 267 ....
completed 268 ....
completed 269 ....
completed 270 ....
completed 271 ....
completed 272 ....
completed 273 ....
completed 274 ....
completed 275 ....
completed 276 ....
completed 277 ....
completed 278 ....
completed 279 ....
completed 280 ....
completed 281 ....
completed 282 ....
completed 283 ....
completed 284 ....
completed 285 ....
completed 286 ....
completed 287 ....
completed 288 ....
completed 289 ....
completed 290 ....
completed 291 ....
completed 292 ....
completed 293 ....
completed 294 ....
completed 295 ....
completed 296 ....
completed 297 ....
completed 298 ....
completed 299 ....
completed 300 ....
completed 301 ....
completed 302 ....
completed 303 ....
completed 304 ....
completed 305 ....
completed 306 ....
completed 307 ....
completed 308 ....
completed 309 ....
completed 310 ....
completed 311 ....
completed 312 ....
completed 313 ....
completed 314 ....
completed 315 ....
completed 316 ....
completed 317 ....
completed 318 ....
completed 319 ....
completed 320 ....
completed 321 ....
completed 322 ....
completed 323 ....
completed 324 ....
completed 325 ....
completed 326 ....
completed 327 ....
completed 328 ....
completed 329 ....
completed 330 ....
completed 331 ....
completed 332 ....
completed 333 ....
completed 334 ....
completed 335 ....
completed 336 ....
completed 337 ....
completed 338 ....
completed 339 ....
completed 340 ....
completed 341 ....
completed 342 ....
completed 343 ....
completed 344 ....
completed 345 ....
completed 346 ....
completed 347 ....
completed 348 ....
completed 349 ....
completed 350 ....
completed 351 ....
completed 352 ....
completed 353 ....
completed 354 ....
completed 355 ....
completed 356 ....
completed 357 ....
completed 358 ....
completed 359 ....
completed 360 ....
completed 361 ....
completed 362 ....
completed 363 ....
completed 364 ....
completed 365 ....
completed 366 ....
completed 367 ....
completed 368 ....
completed 369 ....
completed 370 ....
completed 371 ....
completed 372 ....
completed 373 ....
completed 374 ....
completed 375 ....
completed 376 ....
completed 377 ....
completed 378 ....
completed 379 ....
completed 380 ....
completed 381 ....
completed 382 ....
completed 383 ....
completed 384 ....
completed 385 ....
completed 386 ....
completed 387 ....
completed 388 ....
completed 389 ....
completed 390 ....
completed 391 ....
completed 392 ....
completed 393 ....
completed 394 ....
completed 395 ....
completed 396 ....
completed 397 ....
completed 398 ....
completed 399 ....
completed 400 ....
completed 401 ....
completed 402 ....
completed 403 ....
completed 404 ....
completed 405 ....
completed 406 ....
completed 407 ....
completed 408 ....
completed 409 ....
completed 410 ....
completed 411 ....
completed 412 ....
completed 413 ....
completed 414 ....
completed 415 ....
completed 416 ....
completed 417 ....
completed 418 ....
completed 419 ....
completed 420 ....
completed 421 ....
completed 422 ....
completed 423 ....
completed 424 ....
completed 425 ....
completed 426 ....
completed 427 ....
completed 428 ....
completed 429 ....
completed 430 ....
completed 431 ....
completed 432 ....
completed 433 ....
completed 434 ....
completed 435 ....
completed 436 ....
completed 437 ....
completed 438 ....
completed 439 ....
completed 440 ....
completed 441 ....
completed 442 ....
completed 443 ....
completed 444 ....
completed 445 ....
completed 446 ....
completed 447 ....
completed 448 ....
completed 449 ....
completed 450 ....
completed 451 ....
completed 452 ....
completed 453 ....
completed 454 ....
completed 455 ....
completed 456 ....
completed 457 ....
completed 458 ....
completed 459 ....
completed 460 ....
completed 461 ....
completed 462 ....
completed 463 ....
completed 464 ....
completed 465 ....
completed 466 ....
completed 467 ....
completed 468 ....
completed 469 ....
completed 470 ....
completed 471 ....
completed 472 ....
completed 473 ....
completed 474 ....
completed 475 ....
completed 476 ....
completed 477 ....
completed 478 ....
completed 479 ....
completed 480 ....
completed 481 ....
completed 482 ....
completed 483 ....
completed 484 ....
completed 485 ....
completed 486 ....
completed 487 ....
completed 488 ....
completed 489 ....
completed 490 ....
completed 491 ....
completed 492 ....
completed 493 ....
completed 494 ....
completed 495 ....
completed 496 ....
completed 497 ....
completed 498 ....
completed 499 ....
completed 500 ....
completed 501 ....
completed 502 ....
completed 503 ....
completed 504 ....
completed 505 ....
completed 506 ....
completed 507 ....
completed 508 ....
completed 509 ....
completed 510 ....
completed 511 ....
completed 512 ....
completed 513 ....
completed 514 ....
completed 515 ....
completed 516 ....
completed 517 ....
completed 518 ....
completed 519 ....
completed 520 ....
completed 521 ....
completed 522 ....
completed 523 ....
completed 524 ....
completed 525 ....
completed 526 ....
completed 527 ....
completed 528 ....
completed 529 ....
completed 530 ....
completed 531 ....
completed 532 ....
completed 533 ....
completed 534 ....
completed 535 ....
completed 536 ....
completed 537 ....
completed 538 ....
completed 539 ....
completed 540 ....
completed 541 ....
completed 542 ....
completed 543 ....
completed 544 ....
completed 545 ....
completed 546 ....
completed 547 ....
completed 548 ....
completed 549 ....
completed 550 ....
completed 551 ....
completed 552 ....
completed 553 ....
completed 554 ....
completed 555 ....
completed 556 ....
completed 557 ....
completed 558 ....
completed 559 ....
completed 560 ....
completed 561 ....
completed 562 ....
completed 563 ....
completed 564 ....
completed 565 ....
completed 566 ....
completed 567 ....
completed 568 ....
completed 569 ....
completed 570 ....
completed 571 ....
completed 572 ....
completed 573 ....
completed 574 ....
completed 575 ....
completed 576 ....
completed 577 ....
completed 578 ....
completed 579 ....
completed 580 ....
completed 581 ....
completed 582 ....
completed 583 ....
completed 584 ....
completed 585 ....
completed 586 ....
completed 587 ....
completed 588 ....
completed 589 ....
completed 590 ....
completed 591 ....
completed 592 ....
completed 593 ....
completed 594 ....
completed 595 ....
completed 596 ....
completed 597 ....
completed 598 ....
completed 599 ....
completed 600 ....
completed 601 ....
completed 602 ....
completed 603 ....
completed 604 ....
completed 605 ....
completed 606 ....
completed 607 ....
completed 608 ....
completed 609 ....
completed 610 ....
completed 611 ....
completed 612 ....
completed 613 ....
completed 614 ....
completed 615 ....
completed 616 ....
completed 617 ....
completed 618 ....
completed 619 ....
completed 620 ....
completed 621 ....
completed 622 ....
completed 623 ....
completed 624 ....
completed 625 ....
completed 626 ....
completed 627 ....
completed 628 ....
completed 629 ....
completed 630 ....
completed 631 ....
completed 632 ....
completed 633 ....
completed 634 ....
completed 635 ....
completed 636 ....
completed 637 ....
completed 638 ....
completed 639 ....
completed 640 ....
completed 641 ....
completed 642 ....
completed 643 ....
completed 644 ....
completed 645 ....
completed 646 ....
completed 647 ....
completed 648 ....
completed 649 ....
completed 650 ....
completed 651 ....
completed 652 ....
completed 653 ....
completed 654 ....
completed 655 ....
completed 656 ....
completed 657 ....
completed 658 ....
completed 659 ....
completed 660 ....
completed 661 ....
completed 662 ....
completed 663 ....
completed 664 ....
completed 665 ....
completed 666 ....
completed 667 ....
completed 668 ....
completed 669 ....
completed 670 ....
completed 671 ....
completed 672 ....
completed 673 ....
completed 674 ....
completed 675 ....
completed 676 ....
completed 677 ....
completed 678 ....
completed 679 ....
completed 680 ....
completed 681 ....
completed 682 ....
completed 683 ....
completed 684 ....
completed 685 ....
completed 686 ....
completed 687 ....
completed 688 ....
completed 689 ....
completed 690 ....
completed 691 ....
completed 692 ....
completed 693 ....
completed 694 ....
completed 695 ....
completed 696 ....
completed 697 ....
completed 698 ....
completed 699 ....
completed 700 ....
completed 701 ....
completed 702 ....
completed 703 ....
completed 704 ....
completed 705 ....
completed 706 ....
completed 707 ....
completed 708 ....
completed 709 ....
completed 710 ....
completed 711 ....
completed 712 ....
completed 713 ....
completed 714 ....
completed 715 ....
completed 716 ....
completed 717 ....
completed 718 ....
completed 719 ....
completed 720 ....
completed 721 ....
completed 722 ....
completed 723 ....
completed 724 ....
completed 725 ....
completed 726 ....
completed 727 ....
completed 728 ....
completed 729 ....
completed 730 ....
completed 731 ....
completed 732 ....
completed 733 ....
completed 734 ....
completed 735 ....
completed 736 ....
completed 737 ....
completed 738 ....
completed 739 ....
completed 740 ....
completed 741 ....
completed 742 ....
completed 743 ....
completed 744 ....
completed 745 ....
completed 746 ....
completed 747 ....
completed 748 ....
completed 749 ....
completed 750 ....
completed 751 ....
completed 752 ....
completed 753 ....
completed 754 ....
completed 755 ....
completed 756 ....
completed 757 ....
completed 758 ....
completed 759 ....
completed 760 ....
completed 761 ....
completed 762 ....
completed 763 ....
completed 764 ....
completed 765 ....
completed 766 ....
completed 767 ....
completed 768 ....
completed 769 ....
completed 770 ....
completed 771 ....
completed 772 ....
completed 773 ....
completed 774 ....
completed 775 ....
completed 776 ....
completed 777 ....
completed 778 ....
completed 779 ....
completed 780 ....
completed 781 ....
completed 782 ....
completed 783 ....
completed 784 ....
completed 785 ....
completed 786 ....
completed 787 ....
completed 788 ....
completed 789 ....
completed 790 ....
completed 791 ....
completed 792 ....
completed 793 ....
completed 794 ....
completed 795 ....
completed 796 ....
completed 797 ....
completed 798 ....
completed 799 ....
completed 800 ....
completed 801 ....
completed 802 ....
completed 803 ....
completed 804 ....
completed 805 ....
completed 806 ....
completed 807 ....
completed 808 ....
completed 809 ....
completed 810 ....
completed 811 ....
completed 812 ....
completed 813 ....
completed 814 ....
completed 815 ....
completed 816 ....
completed 817 ....
completed 818 ....
completed 819 ....
completed 820 ....
completed 821 ....
completed 822 ....
completed 823 ....
completed 824 ....
completed 825 ....
completed 826 ....
completed 827 ....
completed 828 ....
completed 829 ....
completed 830 ....
completed 831 ....
completed 832 ....
completed 833 ....
completed 834 ....
completed 835 ....
completed 836 ....
completed 837 ....
completed 838 ....
completed 839 ....
completed 840 ....
completed 841 ....
completed 842 ....
completed 843 ....
completed 844 ....
completed 845 ....
completed 846 ....
completed 847 ....
completed 848 ....
completed 849 ....
completed 850 ....
completed 851 ....
completed 852 ....
completed 853 ....
completed 854 ....
completed 855 ....
completed 856 ....
completed 857 ....
completed 858 ....
completed 859 ....
completed 860 ....
completed 861 ....
completed 862 ....
completed 863 ....
completed 864 ....
completed 865 ....
completed 866 ....
completed 867 ....
completed 868 ....
completed 869 ....
completed 870 ....
completed 871 ....
completed 872 ....
completed 873 ....
completed 874 ....
completed 875 ....
completed 876 ....
completed 877 ....
completed 878 ....
completed 879 ....
completed 880 ....
completed 881 ....
completed 882 ....
completed 883 ....
completed 884 ....
completed 885 ....
completed 886 ....
completed 887 ....
completed 888 ....
completed 889 ....
completed 890 ....
completed 891 ....
completed 892 ....
completed 893 ....
completed 894 ....
completed 895 ....
completed 896 ....
completed 897 ....
completed 898 ....
completed 899 ....
completed 900 ....
completed 901 ....
completed 902 ....
completed 903 ....
completed 904 ....
completed 905 ....
completed 906 ....
completed 907 ....
completed 908 ....
completed 909 ....
completed 910 ....
completed 911 ....
completed 912 ....
completed 913 ....
completed 914 ....
completed 915 ....
completed 916 ....
completed 917 ....
completed 918 ....
completed 919 ....
completed 920 ....
completed 921 ....
completed 922 ....
completed 923 ....
completed 924 ....
completed 925 ....
completed 926 ....
completed 927 ....
completed 928 ....
completed 929 ....
completed 930 ....
completed 931 ....
completed 932 ....
completed 933 ....
completed 934 ....
completed 935 ....
completed 936 ....
completed 937 ....
completed 938 ....
completed 939 ....
completed 940 ....
completed 941 ....
completed 942 ....
completed 943 ....
completed 944 ....
completed 945 ....
completed 946 ....
completed 947 ....
completed 948 ....
completed 949 ....
completed 950 ....
completed 951 ....
completed 952 ....
completed 953 ....
completed 954 ....
completed 955 ....
completed 956 ....
completed 957 ....
completed 958 ....
completed 959 ....
completed 960 ....
completed 961 ....
completed 962 ....
completed 963 ....
completed 964 ....
completed 965 ....
completed 966 ....
completed 967 ....
completed 968 ....
completed 969 ....
completed 970 ....
completed 971 ....
completed 972 ....
completed 973 ....
completed 974 ....
completed 975 ....
completed 976 ....
completed 977 ....
completed 978 ....
completed 979 ....
completed 980 ....
completed 981 ....
completed 982 ....
completed 983 ....
completed 984 ....
completed 985 ....
completed 986 ....
completed 987 ....
completed 988 ....
completed 989 ....
completed 990 ....
completed 991 ....
completed 992 ....
completed 993 ....
completed 994 ....
completed 995 ....
completed 996 ....
completed 997 ....
completed 998 ....
completed 999 ....
completed 1000 ....
completed 1001 ....
completed 1002 ....
completed 1003 ....
completed 1004 ....
completed 1005 ....
completed 1006 ....
completed 1007 ....
completed 1008 ....
completed 1009 ....
completed 1010 ....
completed 1011 ....
completed 1012 ....
completed 1013 ....
completed 1014 ....
completed 1015 ....
completed 1016 ....
completed 1017 ....
completed 1018 ....
completed 1019 ....
completed 1020 ....
completed 1021 ....
completed 1022 ....
completed 1023 ....
completed 1024 ....
completed 1025 ....
completed 1026 ....
completed 1027 ....
completed 1028 ....
completed 1029 ....
completed 1030 ....
completed 1031 ....
completed 1032 ....
completed 1033 ....
completed 1034 ....
completed 1035 ....
completed 1036 ....
completed 1037 ....
completed 1038 ....
completed 1039 ....
completed 1040 ....
completed 1041 ....
completed 1042 ....
completed 1043 ....
completed 1044 ....
completed 1045 ....
completed 1046 ....
completed 1047 ....
completed 1048 ....
completed 1049 ....
completed 1050 ....
completed 1051 ....
completed 1052 ....
completed 1053 ....
completed 1054 ....
completed 1055 ....

### Merge different dataset into a single unified dataset for MachineLearning

In [17]:
final_df = pd.merge(
    merged_df,
    weather_data,
    left_on=[
        "LATITUDE",
        "LONGITUDE",
    ],
    right_on=["latitude", "longitude",],
    how="left",
)

print("\nDone!")
final_df.head()

Done!

,calendar_start_date,calendar_end_date,Year,dengue_total,Location,Month,LONGITUDE,LATITUDE,latitude,longitude,start_date,end_date,monthly_avg_temperature,avg_daily_rain,avg_daily_humidity,avg_daily_soil_moisture,avg_daily_soil_temperature,avg_daily_snowfall,avg_daily_precipitation
0,2022-01-01,2022-01-31,2022,0,ACHHAM,Jan,81.29952,29.113168,29.113168,81.29952,2022-01-01,2022-01-31,6.047159,1.790323,67.417305,0.326501,7.368456,0.006774,1.800000
1,2022-01-01,2022-01-31,2022,0,ACHHAM,Jan,81.29952,29.113168,29.113168,81.29952,2022-02-01,2022-02-28,6.308361,1.728571,68.412598,0.360151,7.201711,0.520000,2.471428
2,2022-01-01,2022-01-31,2022,0,ACHHAM,Jan,81.29952,29.113168,29.113168,81.29952,2022-03-01,2022-03-31,15.462346,0.593548,56.633751,0.306083,11.847374,0.000000,0.593548
3,2022-01-01,2022-01-31,2022,0,ACHHAM,Jan,81.29952,29.113168,29.113168,81.29952,2022-04-01,2022-04-30,19.431221,0.226667,48.587315,0.264947,16.918364,0.000000,0.226667
4,2022-01-01,2022-01-31,2022,0,ACHHAM,Jan,81.29952,29.113168,29.113168,81.29952,2022-05-01,2022-05-31,18.525185,4.190322,68.641037,0.266724,17.781029,0.000000,4.190322

### Drop unnecessary columns
The Columns dropped, either have fulfilled purpose of fetching and merging or they are re-named

In [18]:
final_df.drop(columns=["calendar_start_date", "calendar_end_date", "longitude", "latitude", "LONGITUDE", "LATITUDE", "start_date", "end_date"], inplace=True)

### See No. of Columns

In [19]:
len(final_df.columns)

11

### Understanding Dengue Totals ranges

In [29]:
import numpy as np

dengue = final_df["dengue_total"]

print(f"Total records      : {len(dengue)}")
print(f"Missing values     : {dengue.isna().sum()}")
print(f"Zero cases         : {(dengue == 0).sum()}")
print(f"Non-zero cases     : {(dengue > 0).sum()}")

print("\nBasic Statistics")
print(f"Minimum            : {dengue.min()}")
print(f"Maximum            : {dengue.max()}")
print(f"Mean               : {dengue.mean():.2f}")
print(f"Median             : {dengue.median()}")
print(f"Standard Deviation : {dengue.std():.2f}")

Total records      : 89424
Missing values     : 0
Zero cases         : 32940
Non-zero cases     : 56484

Basic Statistics
Minimum            : 0
Maximum            : 9891
Mean               : 53.36
Median             : 2.0
Standard Deviation : 372.14

In [30]:
# See percintiles
percentiles = [
    0.50,
    0.75,
    0.80,
    0.85,
    0.90,
    0.95,
    0.97,
    0.98,
    0.99,
    0.995,
    0.999
]
print("PERCENTILES")
print(final_df["dengue_total"].quantile(percentiles))

PERCENTILES
0.500       2.0
0.750      11.0
0.800      18.0
0.850      29.0
0.900      53.0
0.950     121.0
0.970     302.0
0.980     473.0
0.990    1151.0
0.995    2212.0
0.999    6016.0
Name: dengue_total, dtype: float64

In [31]:
# Non-Zero
non_zero = final_df.loc[final_df["dengue_total"] > 0, "dengue_total"]

print("Non-Zero Description")
print(non_zero.describe(percentiles=[
    0.10,
    0.25,
    0.50,
    0.75,
    0.90,
    0.95,
    0.99
]))

Non-Zero Description
count    56484.000000
mean        84.485022
std        465.425934
min          1.000000
10%          1.000000
25%          2.000000
50%          7.000000
75%         26.000000
90%         93.000000
95%        274.000000
99%       1809.000000
max       9891.000000
Name: dengue_total, dtype: float64

In [32]:
# Failures in Practical Ranges

bins = [0, 1, 5, 10, 25, 50, 100, 250, 500, 1000, np.inf]

counts = pd.cut(
    final_df.loc[final_df["dengue_total"] > 0, "dengue_total"],
    bins=bins,
    include_lowest=True
).value_counts(sort=False)

print(counts)

dengue_total
(-0.001, 1.0]      10548
(1.0, 5.0]         15264
(5.0, 10.0]         7416
(10.0, 25.0]        8748
(25.0, 50.0]        5328
(50.0, 100.0]       3852
(100.0, 250.0]      2412
(250.0, 500.0]      1188
(500.0, 1000.0]      828
(1000.0, inf]        900
Name: count, dtype: int64

### Classifying the Numeric using the range of total_dengue to dengue_risk
- None (0 dengue)
- Low
- Medium
- High
- Extreme

In [33]:
def classify_dengue(x):
    if x == 0:
        return "No"
    elif x <= 10:
        return "Low"
    elif x <= 50:
        return "Medium"
    elif x <= 250:
        return "High"
    else:
        return "Extreme"

final_df["dengue_level"] = final_df["dengue_total"].apply(classify_dengue)

In [34]:
final_df.head()

,Year,dengue_total,Location,Month,monthly_avg_temperature,avg_daily_rain,avg_daily_humidity,avg_daily_soil_moisture,avg_daily_soil_temperature,avg_daily_snowfall,avg_daily_precipitation,dengue_level
0,2022,0,ACHHAM,Jan,6.047159,1.790323,67.417305,0.326501,7.368456,0.006774,1.800000,No
1,2022,0,ACHHAM,Jan,6.308361,1.728571,68.412598,0.360151,7.201711,0.520000,2.471428,No
2,2022,0,ACHHAM,Jan,15.462346,0.593548,56.633751,0.306083,11.847374,0.000000,0.593548,No
3,2022,0,ACHHAM,Jan,19.431221,0.226667,48.587315,0.264947,16.918364,0.000000,0.226667,No
4,2022,0,ACHHAM,Jan,18.525185,4.190322,68.641037,0.266724,17.781029,0.000000,4.190322,No

In [35]:
# rainfall into classification

final_df["daily_rain_density"] = np.where(
    final_df["avg_daily_rain"] == 0, "no",
    np.where(
        final_df["avg_daily_rain"] <= 2.5, "low",
        np.where(
            final_df["avg_daily_rain"] <= 10, "moderate",
            np.where(
                final_df["avg_daily_rain"] <= 35, "high",
                "extreme"
            )
        )
    )
)


# humidity into classification

final_df["average_humidity"] = np.where(
    final_df["avg_daily_humidity"] < 40, "low",
    np.where(
        final_df["avg_daily_humidity"] < 60, "moderate",
        np.where(
            final_df["avg_daily_humidity"] < 80, "high",
            "extreme"
        )
    )
)


# avg_daily_soil_moisture into classification

final_df["avg_soil_moisture"] = np.where(
    final_df["avg_daily_soil_moisture"] < 0.15, "low",
    np.where(
        final_df["avg_daily_soil_moisture"] < 0.30, "moderate",
        np.where(
            final_df["avg_daily_soil_moisture"] < 0.45, "high",
            "extreme"
        )
    )
)


# avg_daily_soil_temperature into classification

final_df["avg_soil_temperature"] = np.where(
    final_df["avg_daily_soil_temperature"] < 15, "low",
    np.where(
        final_df["avg_daily_soil_temperature"] < 25, "moderate",
        np.where(
            final_df["avg_daily_soil_temperature"] < 35, "high",
            "extreme"
        )
    )
)


# avg_daily_snowfall into classification

final_df["avg_snowfall"] = np.where(
    final_df["avg_daily_snowfall"] == 0, "none",
    np.where(
        final_df["avg_daily_snowfall"] <= 5, "light",
        np.where(
            final_df["avg_daily_snowfall"] <= 20, "moderate",
            "heavy"
        )
    )
)


# avg_daily_precipitation into classification

final_df["avg_precipitation"] = np.where(
    final_df["avg_daily_precipitation"] == 0, "no",
    np.where(
        final_df["avg_daily_precipitation"] <= 2.5, "low",
        np.where(
            final_df["avg_daily_precipitation"] <= 10, "moderate",
            np.where(
                final_df["avg_daily_precipitation"] <= 35, "high",
                "extreme"
            )
        )
    )
)

In [36]:
len(final_df.columns)

18

In [37]:
final_df.head()

,Year,dengue_total,Location,Month,monthly_avg_temperature,avg_daily_rain,avg_daily_humidity,avg_daily_soil_moisture,avg_daily_soil_temperature,avg_daily_snowfall,avg_daily_precipitation,dengue_level,daily_rain_density,average_humidity,avg_soil_moisture,avg_soil_temperature,avg_snowfall,avg_precipitation
0,2022,0,ACHHAM,Jan,6.047159,1.790323,67.417305,0.326501,7.368456,0.006774,1.800000,No,low,high,high,low,light,low
1,2022,0,ACHHAM,Jan,6.308361,1.728571,68.412598,0.360151,7.201711,0.520000,2.471428,No,low,high,high,low,light,low
2,2022,0,ACHHAM,Jan,15.462346,0.593548,56.633751,0.306083,11.847374,0.000000,0.593548,No,low,moderate,high,low,none,low
3,2022,0,ACHHAM,Jan,19.431221,0.226667,48.587315,0.264947,16.918364,0.000000,0.226667,No,low,moderate,moderate,moderate,none,low
4,2022,0,ACHHAM,Jan,18.525185,4.190322,68.641037,0.266724,17.781029,0.000000,4.190322,No,moderate,high,moderate,moderate,none,moderate

In [38]:
final_df = final_df.sample(frac=1, random_state=41, ignore_index=True)
final_df.head()

,Year,dengue_total,Location,Month,monthly_avg_temperature,avg_daily_rain,avg_daily_humidity,avg_daily_soil_moisture,avg_daily_soil_temperature,avg_daily_snowfall,avg_daily_precipitation,dengue_level,daily_rain_density,average_humidity,avg_soil_moisture,avg_soil_temperature,avg_snowfall,avg_precipitation
0,2023,101,KASKI,Jul,14.671596,2.193548,56.372925,0.362452,10.507735,0.000000,2.193548,High,low,moderate,high,low,none,low
1,2024,29,SAPTARI,Sep,28.012848,8.263333,84.643135,0.358635,28.411247,0.000000,8.263333,Medium,moderate,extreme,high,high,none,moderate
2,2024,23,KAILALI,Jul,27.382221,14.126666,84.690079,0.381953,28.406979,0.000000,14.126666,Medium,high,extreme,high,high,none,high
3,2024,4,NUWAKOT,Jun,16.684629,0.110714,56.310810,0.186006,15.823366,0.000000,0.110714,Low,low,moderate,moderate,moderate,none,low
4,2023,0,DOLPA,Nov,-3.726199,0.009677,80.448112,0.379552,-1.395736,1.275806,1.829032,No,low,extreme,high,low,light,low

In [40]:
final_df.to_csv("./datasets/dengu_predictions_in_district_final.csv", index=False)

Train Val test split 70%, 15%, 15%

In [42]:
final_data = pd.read_csv("./datasets/dengu_predictions_in_district_final.csv")
final_data.head()

,Year,dengue_total,Location,Month,monthly_avg_temperature,avg_daily_rain,avg_daily_humidity,avg_daily_soil_moisture,avg_daily_soil_temperature,avg_daily_snowfall,avg_daily_precipitation,dengue_level,daily_rain_density,average_humidity,avg_soil_moisture,avg_soil_temperature,avg_snowfall,avg_precipitation
0,2023,101,KASKI,Jul,14.671596,2.193548,56.372925,0.362452,10.507735,0.000000,2.193548,High,low,moderate,high,low,none,low
1,2024,29,SAPTARI,Sep,28.012848,8.263333,84.643135,0.358635,28.411247,0.000000,8.263333,Medium,moderate,extreme,high,high,none,moderate
2,2024,23,KAILALI,Jul,27.382221,14.126666,84.690080,0.381953,28.406979,0.000000,14.126666,Medium,high,extreme,high,high,none,high
3,2024,4,NUWAKOT,Jun,16.684630,0.110714,56.310810,0.186006,15.823366,0.000000,0.110714,Low,low,moderate,moderate,moderate,none,low
4,2023,0,DOLPA,Nov,-3.726199,0.009677,80.448110,0.379551,-1.395736,1.275806,1.829032,No,low,extreme,high,low,light,low

In [46]:
df = final_data.sample(frac=1, random_state=41).reset_index(drop=True)
df.head()

,Year,dengue_total,Location,Month,monthly_avg_temperature,avg_daily_rain,avg_daily_humidity,avg_daily_soil_moisture,avg_daily_soil_temperature,avg_daily_snowfall,avg_daily_precipitation,dengue_level,daily_rain_density,average_humidity,avg_soil_moisture,avg_soil_temperature,avg_snowfall,avg_precipitation
0,2024,7,KAILALI,Mar,14.063576,0.183871,77.27045,0.294028,17.723722,0.000000,0.183871,Low,low,high,moderate,moderate,none,low
1,2024,22,PARBAT,Jul,13.729439,0.196774,67.91423,0.315847,15.314780,0.000000,0.196774,Medium,low,high,high,moderate,none,low
2,2024,2,DADELDHURA,May,6.982400,1.638710,61.17208,0.422851,5.744254,0.040645,1.696774,Low,low,high,high,low,light,low
3,2022,4,BAJHANG,Aug,9.178739,13.861290,90.26061,0.415069,8.767696,0.000000,13.861290,Low,high,extreme,high,low,none,high
4,2022,19,SINDHUPALCHOK,Nov,16.951458,13.429999,83.17579,0.418400,15.838990,0.000000,13.429999,Medium,high,extreme,high,moderate,none,high

In [47]:
n = len(df)

# Split sizes
train_size = int(0.7 * n)
val_size = int(0.15 * n)

print(train_size)
print(val_size)

62596
13413

In [48]:
train_df = df.iloc[:train_size]
val_df = df.iloc[train_size:train_size + val_size]
test_df = df.iloc[train_size + val_size:]

In [49]:
print("Train:", train_df.shape)
print("Validation:", val_df.shape)
print("Test:", test_df.shape)

Train: (62596, 18)
Validation: (13413, 18)
Test: (13415, 18)

In [51]:
train_df.to_csv("./datasets/train.csv", index=False)
test_df.to_csv("./datasets/test.csv", index=False)
val_df.to_csv("./datasets/val.csv", index=False)