### Download the dataset inside /datasets
- url: alexteboul/diabetes-health-indicators-dataset

### Load dataset and see structure

In [5]:
# import libraries
import pandas as pd
import numpy as np 
pd.set_option('display.max_columns', None)

In [6]:
# load dataset
df = pd.read_csv("./datasets/diabetes_binary.csv")
df.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0

## Analyze dataset and clean

In [7]:
# Human readable and understandable mapping
column_mapping = {
    'Diabetes_binary': 'diabetes_target',
    'HighBP': 'high_bp',
    'HighChol': 'high_cholesterol',
    'CholCheck': 'cholesterol_check_5yrs',
    'BMI': 'bmi',
    'Smoker': 'is_smoker',
    'Stroke': 'has_had_stroke',
    'HeartDiseaseorAttack': 'heart_disease_or_attack',
    'PhysActivity': 'physical_activity',
    'Fruits': 'eats_fruit_daily',
    'Veggies': 'eats_veggies_daily',
    'HvyAlcoholConsump': 'heavy_alcohol',
    'AnyHealthcare': 'has_healthcare',
    'NoDocbcCost': 'no_doc_due_to_cost',
    'GenHlth': 'general_health_rating',
    'MentHlth': 'poor_mental_health_days',
    'PhysHlth': 'poor_physical_health_days',
    'DiffWalk': 'difficulty_walking',
    'Sex': 'sex',
    'Age': 'age_category',
    'Education': 'education_level',
    'Income': 'income_level'
}

df = df.rename(columns=column_mapping)
df.head()

,diabetes_target,high_bp,high_cholesterol,cholesterol_check_5yrs,bmi,is_smoker,has_had_stroke,heart_disease_or_attack,physical_activity,eats_fruit_daily,eats_veggies_daily,heavy_alcohol,has_healthcare,no_doc_due_to_cost,general_health_rating,poor_mental_health_days,poor_physical_health_days,difficulty_walking,sex,age_category,education_level,income_level
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0

In [8]:
# describe the data
df.describe()

,diabetes_target,high_bp,high_cholesterol,cholesterol_check_5yrs,bmi,is_smoker,has_had_stroke,heart_disease_or_attack,physical_activity,eats_fruit_daily,eats_veggies_daily,heavy_alcohol,has_healthcare,no_doc_due_to_cost,general_health_rating,poor_mental_health_days,poor_physical_health_days,difficulty_walking,sex,age_category,education_level,income_level
count,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000
mean,0.500000,0.563458,0.525703,0.975259,29.856985,0.475273,0.062171,0.147810,0.703036,0.611795,0.788774,0.042721,0.954960,0.093914,2.837082,3.752037,5.810417,0.252730,0.456997,8.584055,4.920953,5.698311
std,0.500004,0.495960,0.499342,0.155336,7.113954,0.499392,0.241468,0.354914,0.456924,0.487345,0.408181,0.202228,0.207394,0.291712,1.113565,8.155627,10.062261,0.434581,0.498151,2.852153,1.029081,2.175196
min,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,1.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,7.000000,4.000000,4.000000
50%,0.500000,1.000000,1.000000,1.000000,29.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,9.000000,5.000000,6.000000
75%,1.000000,1.000000,1.000000,1.000000,33.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,4.000000,2.000000,6.000000,1.000000,1.000000,11.000000,6.000000,8.000000
max,1.000000,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

In [9]:
# see if any null values
df.isna().sum()

diabetes_target              0
high_bp                      0
high_cholesterol             0
cholesterol_check_5yrs       0
bmi                          0
is_smoker                    0
has_had_stroke               0
heart_disease_or_attack      0
physical_activity            0
eats_fruit_daily             0
eats_veggies_daily           0
heavy_alcohol                0
has_healthcare               0
no_doc_due_to_cost           0
general_health_rating        0
poor_mental_health_days      0
poor_physical_health_days    0
difficulty_walking           0
sex                          0
age_category                 0
education_level              0
income_level                 0
dtype: int64

In [11]:
df = df.sample(frac=1, random_state=41)

In [12]:
df.to_csv("./datasets/final.csv", index=False)